### PR TITLE
Add php mime type

### PR DESCRIPTION
**Pull request by mallardduck**
While PHP files don't have an official mime type adding these in will allow the package to identify various php extensions. The type used is one prefixed with text since PHP files should be human readable, this allows someone to identify a PHP file as plain text.

It's particularly useful to detect and then display the contents of a PHP file in a web app.

### CODE REVIEW

**Comment by mallardduck** [comment]
So I started looking into why this fails...and I got really confused.
I'm still mostly confused but I think I understand.

In the testDefaultDumpExtensionToType test I dropped a var_dump before and after the assert statement. So it looked like:

```
        var_dump(count($dump));
        $this->assertCount(988, array_keys($dump));
        var_dump(count($dump));
```

When running PHPunit this produced:

```
............../home/dan/Projects/dflydev-apache-mime-types/tests/Dflydev/ApacheMimeTypes/AbstractRepositoryTest.php:92:
int(988)
/home/dan/Projects/dflydev-apache-mime-types/tests/Dflydev/ApacheMimeTypes/AbstractRepositoryTest.php:94:
int(988)
........F/home/dan/Projects/dflydev-apache-mime-types/tests/Dflydev/ApacheMimeTypes/AbstractRepositoryTest.php:92:
int(981)
........F/home/dan/Projects/dflydev-apache-mime-types/tests/Dflydev/ApacheMimeTypes/AbstractRepositoryTest.php:92:
int(981)
.........../home/dan/Projects/dflydev-apache-mime-types/tests/Dflydev/ApacheMimeTypes/AbstractRepositoryTest.php:92:
int(988)
/home/dan/Projects/dflydev-apache-mime-types/tests/Dflydev/ApacheMimeTypes/AbstractRepositoryTest.php:94:
int(988)
....                   47 / 47 (100%)
```

So I guess that means there's something going on in the test (or the code when in testing) that I don't understand. Oddly enough I was able to fix the failure by changing it to:

`        $this->assertCount(count($dump), array_keys($dump));`

The test starts passing; i just don't know how valid of a test that is with this behaviour I can't explain.

**Comment by mallardduck** [comment]
Should see comments above for more info before merging......

........but this should be ready to ship. This does remove tests for older PHP versions that are considered End of Life.

I'm not sure if that's something you'd like to do @simensen; at the least tho it seems like dropping 5.3.x should be done.

**Comment by spotman** [comment]
+1 for merging this!

**Comment by mallardduck** [comment]
Sorry on the terrible follow up. I will look into this again tonight and shoot an updated PR over.

**Comment by mallardduck** [comment]
Might be helpful to merge in #8 before this one - that way we can ensure tests are functional.

**Comment by mallardduck** [comment]
This should be all set for merge now!

**Comment by simensen** [comment]
@mallardduck Now it is my turn for horrible follow-up. I just merged a few other PRs that have been open for awhile. It looks like you have put some work into two separate PR's that both now conflict. If you're up for it, I can probably merge a new PR pretty quickly. If I am not responsive on GitHub, feel free to find me on Twitter and pester me there.

**Comment by mallardduck** [comment]
Absolutely! I will refactor this tonight and shoot the update over ASAP.

**Comment by mallardduck** [comment]
@simensen Good to go!

**Comment by mallardduck** [comment]
@simensen Just redid my refactor - the prior one was just a quick/dirty rebase. This one is a lot more concise.

**Pull request merged**
